name: Forge Test

on:
  workflow_call:
    secrets:
      ALCHEMY_API_KEY_ARBITRUM:
        required: false
        description: Alchemy API key for Arbitrum

jobs:
  test:
    env:
      ALCHEMY_API_KEY_ARBITRUM: ${{ secrets.ALCHEMY_API_KEY_ARBITRUM }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1.2.0
      - run: forge test -vvv
